---
# tasks file for awscli

- block:

    - include_role:
        name: ansible-pip

  when: ansible_distribution_version is version_compare('16.04', '<=')

- block:

    - include_role:
        name: ansible-pip3

  when: ansible_distribution_version is version_compare('20.04', '>=')

- name: ensure awscli is installed using pip
  become: yes
  pip:
    name: awscli
    version: "{{ awscli_version }}"
    executable: "{{ awscli_pip_executable | default(omit) }}"
  tags:
    - awscli